# Use an official Golang runtime as a base image
FROM golang:1.21-alpine

# Set the working directory
WORKDIR /usr/src/app

# Copy go.mod and go.sum files to the workspace
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download



#installing depedencies for auto reload
RUN go install github.com/cosmtrek/air@latest

Copy . . 


RUN ls -al /usr/src/app



# Expose the port the app runs on
EXPOSE 9000

